name: eljur_students
description: Unofficial Eljur client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  oxidized: ^6.1.0
  sembast: ^3.5.0+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  dio: ^5.3.4
  get_it: ^7.6.4
  path_provider: ^2.1.1
  path: ^1.8.3
  event_listener: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path_android: "assets/images/logo-full.png"
  android: true
  adaptive_icon_background: "#910000"
  adaptive_icon_foreground: "assets/images/logo-fg.png"